// Styles, Theming & Fonts
import '@/styles/globals.css';
import { Providers } from './providers';
import { Inter } from 'next/font/google';

const inter = Inter({ subsets: ['latin'], variable: '--font-inter' });

// SEO & Metadata
import type { Metadata } from 'next';
import ThemeSwitch from '@/components/atom/ThemeSwitch';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
};

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${inter.variable} font-primary`}>
      <body className="bg-white-700 dark:bg-black-900 text-black-900 dark:text-white-700">
        <Providers>
          <main>{children}</main>
          <div className="fixed bottom-[0px] right-5 bg-red-500 dark:bg-blue-500 p-2">
            <ThemeSwitch />
          </div>
        </Providers>
      </body>
    </html>
  );
}
